FROM rust:1.89-slim-bookworm

RUN apt-get update && apt-get install -y pkg-config libssl-dev chromium && rm -rf /var/lib/apt/lists/*
ENV CHROME_BIN=/usr/bin/chromium
RUN cargo install cargo-watch --locked

WORKDIR /app
EXPOSE 3000
CMD ["cargo", "watch", "-i", "*.md", "-i", "docs/*", "-i", "modules/admin-app/*", "-i", "modules/search-app/*", "-i", "target/*", "-x", "run --bin api"]
