FROM rust:1.93-slim-bookworm

RUN apt-get update && apt-get install -y pkg-config libssl-dev chromium && rm -rf /var/lib/apt/lists/*
RUN cargo install cargo-watch

WORKDIR /app
ENV CHROME_BIN=/usr/bin/chromium
ENV PORT=9080
EXPOSE 9080 9081

CMD ["cargo", "watch", "-x", "run --bin run-migrations", "-s", "cargo run --bin rootsignal-server"]
