use crate::{sql, data, Migration};
use crate::data_migrations::backfill_location_geocoded;

pub fn migrations() -> Vec<Migration> {
    vec![
        sql("001_create_web_interactions",       include_str!("../migrations/001_create_web_interactions.sql")),
        sql("002_add_semantics_column",          include_str!("../migrations/002_add_semantics_column.sql")),
        sql("003_rename_city_slug_to_region_slug", include_str!("../migrations/003_rename_city_slug_to_region_slug.sql")),
        sql("004_content_type_tables",           include_str!("../migrations/004_content_type_tables.sql")),
        sql("005_post_metadata",                 include_str!("../migrations/005_post_metadata.sql")),
        sql("006_scout_runs",                    include_str!("../migrations/006_scout_runs.sql")),
        sql("007_unified_events",                include_str!("../migrations/007_unified_events.sql")),
        sql("008_source_fetch_count",            include_str!("../migrations/008_source_fetch_count.sql")),
        sql("009_scout_run_events",              include_str!("../migrations/009_scout_run_events.sql")),
        sql("010_drop_parent_id_fk",             include_str!("../migrations/010_drop_parent_id_fk.sql")),
        sql("011_validation_issues",             include_str!("../migrations/011_validation_issues.sql")),
        sql("012_url_scrape_stats",              include_str!("../migrations/012_url_scrape_stats.sql")),
        sql("013_lint_event_columns",            include_str!("../migrations/013_lint_event_columns.sql")),
        sql("014_event_summary_column",          include_str!("../migrations/014_event_summary_column.sql")),
        sql("015_node_event_indexes",            include_str!("../migrations/015_node_event_indexes.sql")),
        sql("016_event_uuid_columns",            include_str!("../migrations/016_event_uuid_columns.sql")),
        sql("017_aggregate_snapshots",           include_str!("../migrations/017_aggregate_snapshots.sql")),
        sql("018_replay_checkpoints",            include_str!("../migrations/018_replay_checkpoints.sql")),
        sql("019_run_events_jsonb",              include_str!("../migrations/019_run_events_jsonb.sql")),
        sql("020_event_correlation_and_aggregate", include_str!("../migrations/020_event_correlation_and_aggregate.sql")),
        sql("021_drop_scout_run_events",         include_str!("../migrations/021_drop_scout_run_events.sql")),
        sql("022_add_handler_id",                include_str!("../migrations/022_add_handler_id.sql")),
        sql("023_seesaw_store_tables",           include_str!("../migrations/023_seesaw_store_tables.sql")),
        sql("024_seesaw_cancellations",          include_str!("../migrations/024_seesaw_cancellations.sql")),
        sql("025_scope_snapshots_by_correlation", include_str!("../migrations/025_scope_snapshots_by_correlation.sql")),
        sql("026_scout_runs_flow_columns",       include_str!("../migrations/026_scout_runs_flow_columns.sql")),
        sql("027_fix_finished_at_nullable",      include_str!("../migrations/027_fix_finished_at_nullable.sql")),
        sql("028_events_run_variant_index",      include_str!("../migrations/028_events_run_variant_index.sql")),
        sql("029_seesaw_handler_logs",           include_str!("../migrations/029_seesaw_handler_logs.sql")),
        sql("030_seesaw_handler_descriptions",   include_str!("../migrations/030_seesaw_handler_descriptions.sql")),
        sql("031_deferred_scrapes",              include_str!("../migrations/031_deferred_scrapes.sql")),
        sql("032_rename_scheduled_scrapes",      include_str!("../migrations/032_rename_scheduled_scrapes.sql")),
        sql("033_budget_configs",                include_str!("../migrations/033_budget_configs.sql")),
        sql("034_simplify_budget",               include_str!("../migrations/034_simplify_budget.sql")),
        sql("035_seesaw_026_schema",             include_str!("../migrations/035_seesaw_026_schema.sql")),
        sql("036_backfill_sources_discovered",  include_str!("../migrations/036_backfill_sources_discovered.sql")),
        sql("037_events_correlation_seq_index", include_str!("../migrations/037_events_correlation_seq_index.sql")),
        data("038_backfill_location_geocoded", backfill_location_geocoded::plan, backfill_location_geocoded::run),
        sql("039_rename_replay_pointer",       include_str!("../migrations/039_rename_replay_pointer.sql")),
    ]
}
